### ISSUE TITLE
epghub 能否添加一个操作指引

### ISSUE THREAD

**Issue by kasen-zhang** [riverscn/epghub#3]
大佬你好，我是一个小白，我目前在用openwrt这个软路由系统，由于不懂命令，能否大佬提供个配置和部署的命令指引？

**Comment by riverscn** [comment]
openwrt 如果安装了 docker 可以参考 docker 部分部署。否则请选择用 Cloudflare 来部署。

**Comment by kasen-zhang** [comment]
> openwrt 如果安装了 docker 可以参考 docker 部分部署。否则请选择用 Cloudflare 来部署。

我在docker中部署的过程中提示错误，看不太懂，想请大佬指导下。
<img width="1044" alt="微信图片_20231110164808" src="https://github.com/riverscn/epghub/assets/148027164/a05ca67e-fde2-4612-9f18-d93729590a32">
——————————————————————————————————————————————
root@H69K-CPE:/mnt/sda1/epghub# docker compose up --build -d
[+] Running 9/9
 ✔ server 8 layers [⣿⣿⣿⣿⣿⣿⣿⣿]      0B/0B      Pulled                                                                                                                                              105.2s 
   ✔ 8024d4fb53b2 Pull complete                                                                                                                                                                     5.9s 
   ✔ 3d826ee8aa65 Pull complete                                                                                                                                                                     3.8s 
   ✔ 198068495d09 Pull complete                                                                                                                                                                     6.4s 
   ✔ 509db9a897ae Pull complete                                                                                                                                                                    17.8s 
   ✔ cd10c9e0405a Pull complete                                                                                                                                                                     7.7s 
   ✔ 7b94995164a1 Pull complete                                                                                                                                                                    11.7s 
   ✔ 8b840bd562db Pull complete                                                                                                                                                                    12.5s 
   ✔ 7ab0b1cfc5b7 Pull complete                                                                                                                                                                    13.7s 
[+] Building 527.5s (6/17)                                                                                                                                                                docker:default
 => [builder internal] load build definition from dockerfile                                                                                                                                        0.1s
 => => transferring dockerfile: 779B                                                                                                                                                                0.0s
 => [builder internal] load .dockerignore                                                                                                                                                           0.0s
 => => transferring context: 2B                                                                                                                                                                     0.0s
 => [builder internal] load metadata for docker.io/library/python:3.11-buster                                                                                                                       5.3s
 => [builder internal] load build context                                                                                                                                                           0.1s
 => => transferring context: 157.37kB                                                                                                                                                               0.0s
 => [builder  1/13] FROM docker.io/library/python:3.11-buster@sha256:3a19b4d6ce4402d11bb19aa11416e4a262a60a57707a5cda5787a81285df2666                                                             280.6s
 => => resolve docker.io/library/python:3.11-buster@sha256:3a19b4d6ce4402d11bb19aa11416e4a262a60a57707a5cda5787a81285df2666                                                                         0.0s
 => => sha256:e7349847b3241e237d7a69174fea45593592e320324afdbae5c685b0a96e8181 17.45MB / 17.45MB                                                                                                   71.1s
 => => sha256:3a19b4d6ce4402d11bb19aa11416e4a262a60a57707a5cda5787a81285df2666 988B / 988B                                                                                                          0.0s
 => => sha256:47473ed41b98c5468f6c01f65cea4c2f0f90e399bf3f809f135c6231d715bae2 7.54kB / 7.54kB                                                                                                      0.0s
 => => sha256:e8371d57f7426517aead21bff5af0cf321625cac166c86214c439fb67db84243 49.24MB / 49.24MB                                                                                                  154.0s
 => => sha256:f104dc4fba2c93f994673ea6c81b78ad44ef6b4d6984576abf9be7cf0dde960b 52.22MB / 52.22MB                                                                                                  149.2s
 => => sha256:9766f601631b3802278c589495879bb2ff5fbc554d729662cd30731583217bbb 2.01kB / 2.01kB                                                                                                      0.0s
 => => sha256:1879ae1722a31ce8aedfe4a10df652902581eab286fbbdd253684bf6ceb94cce 183.46MB / 183.46MB                                                                                                232.4s
 => => sha256:a82b33408f1ca71a98de8cccd0b2a6ad4fded1721b2bbce30a0c0c98a1912952 6.26MB / 6.26MB                                                                                                    154.1s
 => => sha256:cec6ede40ade05e73617c63694f3cabaa51a0ce20fa56ad5ac02889236a26746 22.08MB / 22.08MB                                                                                                  165.4s
 => => sha256:4e1ecbe8c78c6555883536df1a08cfa138dcccd0645e3f36ce4637c86ff85c85 244B / 244B                                                                                                        154.8s
 => => extracting sha256:e8371d57f7426517aead21bff5af0cf321625cac166c86214c439fb67db84243                                                                                                           7.6s
 => => sha256:954d693af3994fc41d4cf5d1509a624db0edaca49767486752cc7592b1749e26 3.09MB / 3.09MB                                                                                                    157.5s
 => => extracting sha256:e7349847b3241e237d7a69174fea45593592e320324afdbae5c685b0a96e8181                                                                                                           2.0s
 => => extracting sha256:f104dc4fba2c93f994673ea6c81b78ad44ef6b4d6984576abf9be7cf0dde960b                                                                                                          10.5s
 => => extracting sha256:1879ae1722a31ce8aedfe4a10df652902581eab286fbbdd253684bf6ceb94cce                                                                                                          39.3s
 => => extracting sha256:a82b33408f1ca71a98de8cccd0b2a6ad4fded1721b2bbce30a0c0c98a1912952                                                                                                           1.4s
 => => extracting sha256:cec6ede40ade05e73617c63694f3cabaa51a0ce20fa56ad5ac02889236a26746                                                                                                           5.1s
 => => extracting sha256:4e1ecbe8c78c6555883536df1a08cfa138dcccd0645e3f36ce4637c86ff85c85                                                                                                           0.0s
 => => extracting sha256:954d693af3994fc41d4cf5d1509a624db0edaca49767486752cc7592b1749e26                                                                                                           1.0s
 => ERROR [builder  2/13] RUN pip install poetry==1.4.2                                                                                                                                           241.4s
------                                                                                                                                                                                                   
 > [builder  2/13] RUN pip install poetry==1.4.2:                                                                                                                                                        
41.05 WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffaed76bd0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/                                                                                
73.59 WARNING: Retrying (Retry(total=3, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffaed772d0>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/                                                                                
106.6 WARNING: Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffaed66450>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
140.7 WARNING: Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffaed67190>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
176.7 WARNING: Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<pip._vendor.urllib3.connection.HTTPSConnection object at 0xffffaed77b50>: Failed to establish a new connection: [Errno -3] Temporary failure in name resolution')': /simple/poetry/
208.8 ERROR: Could not find a version that satisfies the requirement poetry==1.4.2 (from versions: none)
208.8 ERROR: No matching distribution found for poetry==1.4.2
------
failed to solve: executor failed running [/bin/sh -c pip install poetry==1.4.2]: exit code: 1

**Comment by riverscn** [comment]
你仔细读，就是网络连接的问题
