### ISSUE TITLE
提个小bug

### ISSUE THREAD

**Issue by x2009again** [riverscn/epghub#5]
我把volumes修改了目录，发现一直有问题，后面才发现，server里面是访问的docker/web，也就是说如果改了之后其实server已经无法访问docker/web，甚至也无法访问builder容器里面的/epghub目录下的内容。
哦，还有一个小建议，建议poetry升级到1.5.0或者以上，支持mirrors，不然国内安装依赖会失败。

**Comment by riverscn** [comment]
> 我把volumes修改了目录，发现一直有问题，后面才发现，server里面是访问的docker/web，也就是说如果改了之后其实server已经无法访问docker/web，甚至也无法访问builder容器里面的/epghub目录下的内容。

这不是bug。wrangler 本身需要在项目的跟目录运行，因为它需要读取 function 目录。所以如果你想更改 web 目录的位置，你需要同时修改 docker-compose 中的 wrangler 启动参数。
