### ISSUE TITLE
docker 24.0.7 无法部署该项目

### ISSUE THREAD

**Issue by yue365** [riverscn/epghub#8]
[root@localhost epghub-main]# docker --version
Docker version 24.0.7, build afdd53b

[root@localhost epghub-main]# docker-compose up --build -d
ERROR: The Compose file './docker-compose.yaml' is invalid because:
services.server.healthcheck value Additional properties are not allowed ('start_period' was unexpected)
services.builder.depends_on contains an invalid type, it should be an array
[root@localhost epghub-main]#

**Comment by riverscn** [comment]
Try docker version 25.
